print("AND : {}".format(10 & 10))
print("OR : {}".format(10 | 11))
print("XOR : {}".format(10 ^ 10))
print("NOT : {}".format(~11))
print("RIGHT : {}".format(10 << 1))
print("RIGHT : {}".format(10 << 2))
print("RIGHT : {}".format(12 << 2))
print("RIGHT : {}".format(20 << 2))
print("RIGHT : {}".format(20 << 3))
print("LEFT : {}".format(10 >> 2))
print("RIGHT : {}".format(12 >> 2))
print("RIGHT : {}".format(20 >> 2))
